build

diff --git a/circle.yml b/circle.yml
--- a/circle.yml
+++ b/circle.yml
@@ -1,4 +1,8 @@
 machine:
+  timezone:
+    Europe/Berlin
+  java:
+    version: oraclejdk8
   environment:
     MAKEFLAGS: "j4"
 # --- Android build ---
@@ -24,6 +28,20 @@ machine:
     # c-toxcore v0.1.7
     AND_CTOXCORE_VERSION: "48c86e942d487a8856cbd25797b320bfb1879ddc"
 
+    _SDK_: /usr/local/android-sdk-linux/
+    _JAVA_OPTIONS: "-Xms512m -Xmx1024m"
+    JAVA_OPTS: "-Xms512m -Xmx1024m"
+    GRADLE_OPTS: '-Xmx512m -Dorg.gradle.jvmargs="-Xmx1700m -XX:+HeapDumpOnOutOfMemoryError -XX:MaxPermSize=1700m"'
+    CLASS_P: com.zoffcc.applications.trifa
+    START_INTENT_P: com.zoffcc.applications.trifa.MainActivity
+
+    ZEMU_: "appemu23"
+    EMU_: "appemu21"
+    XEMU_: "appemu10"
+    Zsdpath: "/sdcard"
+    sdpath: "/storage/sdcard"
+    Xsdpath: "/mnt/sdcard"
+
 dependencies:
   pre:
   - sudo apt-get update
@@ -40,6 +58,39 @@ dependencies:
   - clang --version ; exit 0
 
   - mkdir -p /home/ubuntu/c-toxcore # workaround :-)
+
+
+  - sudo apt-get install xdotool > /dev/null 2> /dev/null
+  - sudo apt-get install telnet > /dev/null 2> /dev/null
+  - sudo apt-get install x11-utils > /dev/null 2> /dev/null
+  - sudo apt-get install xvkbd > /dev/null 2> /dev/null
+  - sudo apt-get install qrencode > /dev/null 2> /dev/null
+  - sudo apt-get install p7zip-full
+
+  - echo y | android update sdk --no-ui --all --filter "tools"
+  - android list sdk --all | grep -i tools
+  - android list sdk --all --extended
+
+  - echo y | android update sdk --no-ui --all --filter build-tools-23.0.3
+  - echo y | android update sdk --no-ui --all --filter build-tools-24.0.2
+  - echo y | android update sdk --no-ui --all --filter build-tools-25.0.2
+  - echo y | android update sdk --no-ui --all --filter android-16 ; exit 0
+  - echo y | android update sdk --no-ui --all --filter android-21
+  - echo y | android update sdk --no-ui --all --filter android-23
+  - echo y | android update sdk --no-ui --all --filter android-24
+  - echo y | android update sdk --no-ui --all --filter android-25
+  - echo y | android update sdk --no-ui --all --filter platform-tools
+
+  - echo y | android update sdk --no-ui --all --filter extra-android-m2repository > /dev/null 2> /dev/null
+  - echo y | android update sdk --no-ui --all --filter extra-google-m2repository > /dev/null 2> /dev/null
+  - echo y | android update sdk --no-ui --all --filter extra-android-support > /dev/null 2> /dev/null
+
+  - echo y | android update sdk --no-ui --all --filter platform-tools-preview > /dev/null 2> /dev/null
+  - echo y | android update sdk --no-ui --all --filter sys-img-armeabi-v7a-android-21
+  - echo y | android update sdk --no-ui --all --filter sys-img-armeabi-v7a-android-23 > /dev/null 2> /dev/null
+  - echo y | android update sdk --no-ui --all --filter sys-img-armeabi-v7a-addon-google_apis-google-23 > /dev/null 2> /dev/null
+  - echo y | android update sdk --no-ui --all --filter addon-google_apis-google-23 > /dev/null 2> /dev/null
+
 
 compile:
   override:
@@ -141,11 +192,125 @@ compile:
   - . ~/pp;cd jni-c-toxcore/; $READELF -A libjni-c-toxcore.so
   - . ~/pp;cd jni-c-toxcore/; cp -av libjni-c-toxcore.so $CIRCLE_ARTIFACTS/android/libs/armeabi/
 
-  - cd jni-c-toxcore/; cp -av libjni-c-toxcore.so android-refimpl-app/
-
+  - cd jni-c-toxcore/; cp -av libjni-c-toxcore.so android-refimpl-app/app/nativelibs/armeabi/
 # --- Android build ---
+
+
+# --------- GRADLE -------------
+  - cd jni-c-toxcore/android-refimpl-app/ ; ./gradlew build --max-workers=1 --stacktrace --no-daemon || ./gradlew build --stacktrace --no-daemon # first build may FAIL
+# --------- GRADLE -------------
+
+
+# --- save lint output ---
+    - cd jni-c-toxcore/android-refimpl-app/ ; find . -name '*lint-report*' -exec ls -al {} \; ; exit 0
+    - cd jni-c-toxcore/android-refimpl-app/ ; cp -av ./app/lint-report.html $CIRCLE_ARTIFACTS/ ; exit 0
+    - cd jni-c-toxcore/android-refimpl-app/ ; cp -av ./app/lint-report.xml $CIRCLE_ARTIFACTS/ ; exit 0
+    - cd jni-c-toxcore/android-refimpl-app/ ; cp -av ./lint-report.txt $CIRCLE_ARTIFACTS/ ; exit 0
+# --- save lint output ---
+
+# ----------- show generated apk file -----------
+    - cd jni-c-toxcore/android-refimpl-app/ ; ls -al app/build/outputs/apk/ ; exit 0
+    - cd jni-c-toxcore/android-refimpl-app/ ; find ./ -name '*.apk' ; exit 0
+# ----------- show generated apk file -----------
+
+
+
+
+# ----------- make zipfile for builds [for download-dependencies.sh] -----------
+    #- . f;mkdir -p ~/and_stud_prj/app/libs/
+    #- . f;cp -av app/libs/tox*jar ~/and_stud_prj/app/libs/
+    #- . f;mkdir -p ~/and_stud_prj/app/src/main/jniLibs/
+    #- . f;cp -av app/src/main/jniLibs/* ~/and_stud_prj/app/src/main/jniLibs/
+    #- . f;cd ~/and_stud_prj/ ; zip -r $CIRCLE_ARTIFACTS/supplement.zip *
+# ----------- make zipfile for builds [for download-dependencies.sh] -----------
+
+    - zip -d app/build/outputs/apk/app-release-unsigned.apk META-INF/\*     # remove signature !!
+    - cp -av app/build/outputs/apk/app-release-unsigned.apk ~/app.apk ;
+      cd ~/ ;
+      echo xxxxxxrm -f ~/.android/debug.keystore ;
+      ls -al ~/.android/debug.keystore ;
+      if [ ! -f ~/.android/debug.keystore ]; then echo "*** generating new signer key ***" ;
+      echo "*** generating new signer key ***";
+      echo "*** generating new signer key ***";
+      keytool -genkey -v -keystore ~/.android/debug.keystore -storepass android -keyalg RSA -keysize 2048 -validity 10000 -alias androiddebugkey -keypass android -dname "CN=Android Debug,O=Android,C=US" ;
+      fi ;
+      ls -al ~/ ;
+      jarsigner -verbose -keystore ~/.android/debug.keystore -storepass android -keypass android -sigalg SHA1withRSA -digestalg SHA1 -sigfile CERT -signedjar app-signed.apk app.apk androiddebugkey ;
+      ls -al ~/ ;
+      $_SDK_/build-tools/23.0.3/zipalign -v 4 app-signed.apk app-signed-aligned.apk ;
+      ls -al ~/ ;
+      pwd ;
+      ls -al ;
+      cp -av app-signed-aligned.apk $CIRCLE_ARTIFACTS/${CIRCLE_PROJECT_REPONAME}.apk || exit 1
+
+##   also make apk files with different names for each build (for individual downloads)
+    - cp -av $CIRCLE_ARTIFACTS/${CIRCLE_PROJECT_REPONAME}.apk $CIRCLE_ARTIFACTS/${CIRCLE_PROJECT_REPONAME}_circleci_$CIRCLE_SHA1.apk
+##   qr code to scan with your phone to directly download the apk file (for convenience)
+    - qrencode -o $CIRCLE_ARTIFACTS/QR_apk.png 'https://circle-artifacts.com/gh/'${CIRCLE_PROJECT_USERNAME}'/'${CIRCLE_PROJECT_REPONAME}'/'${CIRCLE_BUILD_NUM}'/artifacts/'${CIRCLE_NODE_INDEX}'/tmp/'`basename $CIRCLE_ARTIFACTS`'/'"${CIRCLE_PROJECT_REPONAME}_circleci_$CIRCLE_SHA1.apk" ; exit 0
+##   qr code to go directly to the aritfacts (to scan with phone)
+    - qrencode -o $CIRCLE_ARTIFACTS/QR_artifacts.png 'https://circleci.com/gh/'${CIRCLE_PROJECT_USERNAME}'/'${CIRCLE_PROJECT_REPONAME}'/'${CIRCLE_BUILD_NUM}'#artifacts' ; exit 0
+
+
+
+  pre:
+    - mksdcard -l e 180M sdcard.img
+    - echo 'mtools_skip_check=1' > ~/.mtoolsrc
+    - android list targets
+#
+    - if [ "$EMU_" == "appemu23" ]; then echo "no" | android create avd -n appemu23 -f -t android-23 --abi default/armeabi-v7a --skin "WXGA720" ; fi
+    - if [ "$EMU_" == "appemu23" ]; then cat ~/.android/avd/appemu23.avd/config.ini ; fi
+#
+    - if [ "$EMU_" == "appemu21" ]; then echo "no" | android create avd -n appemu21 -f -t android-21 --abi default/armeabi-v7a --skin "WXGA720" ; fi
+    - if [ "$EMU_" == "appemu21" ]; then cat ~/.android/avd/appemu21.avd/config.ini ; fi
+#
+    - if [ "$EMU_" == "appemu10" ]; then echo "no" | android create avd -n appemu10 -f -t android-10 --abi default/armeabi --skin "WQVGA432" ; fi
+    - if [ "$EMU_" == "appemu10" ]; then cat ~/.android/avd/appemu10.avd/config.ini ; fi
+#
+    - echo "$EMU_"
+    - echo "$sdpath"
+
 
 test:
   override:
-  - ls -alR "$_toolchain_"/arm-linux-androideabi/sysroot/usr/lib/
+    - ls -alR "$_toolchain_"/arm-linux-androideabi/sysroot/usr/lib/
+
+    - emulator -avd "$EMU_" -sdcard sdcard.img -no-audio:
+        background: true
+        parallel: true
+    - circle-android wait-for-boot
+
+    - sleep 210 # let the emulator settle down first
+
+    - adb shell input keyevent 82 # remove lock screen on emulator
+    - sleep 10
+    - import -window root $CIRCLE_ARTIFACTS/capture_emulator_running.png
+
+    - adb shell "cat /proc/meminfo" ; exit 0
+
+    - adb shell ls -al / ; exit 0
+    - adb shell ls -al /storage/ ; exit 0
+    - adb shell ls -al /sdcard/ ; exit 0
+
+    - adb install ~/app-signed-aligned.apk
+
+    - adb logcat -v time > $CIRCLE_ARTIFACTS/adb_out.txt 2>&1 :
+        background: true
+    - sleep 60 # let the emulator settle down first
+
+    - adb shell am start -n $CLASS_P/$START_INTENT_P
+    - sleep 60
+    - sleep 120 # wait to be sure the app has started fully
+
+    - died_count=`cat $CIRCLE_ARTIFACTS/adb_out.txt|grep 'Process. '"$CLASS_P"', PID.'|wc -l|tr -d ' '` ; if [ $died_count -gt 0 ]; then echo "app crashed"; exit 1; fi
+
+    - import -window root $CIRCLE_ARTIFACTS/capture_app_running.png # get proof that the app is running
+    - adb shell screencap -p | sed 's/\r$//' > $CIRCLE_ARTIFACTS/capture_app_running_2.png
+
+# ----- CI artifact cleanup -----
+    - mkdir -p $CIRCLE_ARTIFACTS/other/
+    - mv -v $CIRCLE_ARTIFACTS/adb_out.txt $CIRCLE_ARTIFACTS/other/
+    - mv -v $CIRCLE_ARTIFACTS/stderr*.txt $CIRCLE_ARTIFACTS/other/
+    - mv -v $CIRCLE_ARTIFACTS/stdout*.txt $CIRCLE_ARTIFACTS/other/
+# ----- CI artifact cleanup -----
+
 
